name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5

      - name: Install SWIG for Linux
        if: runner.os == "Linux"
        run: |
          sudo apt-get install swig
      
      - name: Install SWIG for macOS
        if: runner.os == "macOS"
        run: |
          brew install swig

      - name: Install Visual C++ and SWIG
        if: runner.os == 'Windows'
        run: |
          choco install swig -f -y
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
